name: Build and Deploy
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: cd shiraberu-client && npm install
      - name: Build
        run: npm run build
      - name: Download Firebase
        run: curl -sL https://firebase.tools | bash
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}