name: Build and Deploy
on: [push, pull_request]

jobs:
  build:
    name: Build
    
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
    
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Download Firebase
        run: npm install -g firebase-tools
      - name: Download eslint
        run: npm install -g eslint
      - name: Download eslint-plugin-promise
        run: npm install eslint-plugin-promise@latest --save-dev
      - name: Install Dependencies
        working-directory: ./shiraberu-client
        run: npm install
      - name: Build
        working-directory: ./shiraberu-client
        run: npm run build
      - name: Deploy to Firebase
        working-directory: ./shiraberu-client
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
