name: Test Frontend Code
on: [push, pull_request]

jobs:
  emulator_test:
    name: Run frontend tests using jest
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules # checkout rest
      shell: bash
      run: |
        # If your submodules are configured to use SSH instead of HTTPS please uncomment the following line
        # git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Install dependedncies
      run: npm install
      working-directory: shiraberu-client
    - name: Run all tests
      run: npm test
      working-directory: shiraberu-client
